[package]
name = "sifis-generate"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Generate a new project for some build systems with the use of templates."
repository = "https://github.com/sifis-home/sifis-generate"
homepage = "https://github.com/sifis-home/sifis-generate"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
license = "1.1"
minijinja = { version = "0.14", features = ["source"] }
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
textwrap = "0.14"
arg_enum_proc_macro = "0.3.2"
lazy_static = "1.4"
