[package]
name = "sifis-tool"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Project management tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
minijinja = "0.5"
anyhow = "1"
